# Generated by Django 5.2.3 on 2025-06-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_taskdetails_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(default=1, related_name='tasks', to='tasks.employee'),
        ),
    ]
